/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Sat Jan 30 2016 19:42:14 GMT+0800 (CST).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase'
], function (
    PluginConfig,
    PluginBase) {
    'use strict';

    /**
     * Initializes a new instance of DisplayGraphDiff.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin DisplayGraphDiff.
     * @constructor
     */
    var DisplayGraphDiff = function () {
        // Call base class' constructor.
        PluginBase.call(this);
    };

    // Prototypal inheritance from PluginBase.
    DisplayGraphDiff.prototype = Object.create(PluginBase.prototype);
    DisplayGraphDiff.prototype.constructor = DisplayGraphDiff;

    /**
     * Gets the name of the DisplayGraphDiff.
     * @returns {string} The name of the plugin.
     * @public
     */
    DisplayGraphDiff.prototype.getName = function () {
        return 'DisplayGraphDiff';
    };

    /**
     * Gets the semantic version (semver.org) of the DisplayGraphDiff.
     * @returns {string} The version of the plugin.
     * @public
     */
    DisplayGraphDiff.prototype.getVersion = function () {
        return '0.1.0';
    };

    DisplayGraphDiff.prototype.getConfigStructure = function () {
        //var self = this,
            //branchesResponse = $.ajax({url: "api/projects/" + self.projectId.replace("+", "/") + "/branches", async: false}).responseJSON,
            //branches = branchesResponse ? Object.keys(branchesResponse) : [];
        return [
            {
                name: 'branch1Name',
                displayName: 'First branch name',
                description: 'Select the first branch to compare',
                value: 'master',
                valueType: 'string',
                valueItems: ['master', 'alter'],
                readOnly: false
            },
            {
                name: 'branch2Name',
                displayName: 'Second branch name',
                description: 'Select the second branch to compare',
                value: 'alter',
                valueType: 'string',
                valueItems: ['master', 'alter'],
                readOnly: false
            }
        ];
    };

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    DisplayGraphDiff.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            nodeObject;


        // Using the logger.
        self.logger.debug('This is a debug message.');
        self.logger.info('This is an info message.');
        self.logger.warn('This is a warning message.');
        self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.

        // todo: in the plugin window show a list of available branches

        // todo: allow user to select 2 branches to compare
        self.currentConfig = self.getCurrentConfig();
        var b1 = self.currentConfig.branch1Name,
            b2 = self.currentConfig.branch2Name,
            url = "/api/projects/" + self.projectId.replace("+", "/") + "/compare/" + b1 + "..." + b2;

        var result = $.ajax({url: url, async: false}).responseJSON;



        // todo: when plugin runs, it updates the color attributes of graph view of the two branches

        // todo: when two versions are the same, use default colors; when different, use other colors

        nodeObject = self.activeNode;

        self.core.setAttribute(nodeObject, 'name', 'My new obj');
        self.core.setRegistry(nodeObject, 'position', {x: 70, y: 70});


        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.
        self.save('DisplayGraphDiff updated model.', function (err) {
            if (err) {
                callback(err, self.result);
                return;
            }
            self.result.setSuccess(true);
            callback(null, self.result);
        });

    };

    return DisplayGraphDiff;
});